Repository Drakkar-Software/OctoBot, pull requests merged in 2019-05, with the labels that each got.

#862 [README] introduce active bots counter badge
  README.md
Labels: documentation, review

#868 Update badge month counter
  README.md
Labels: documentation, review

#879 #875 fixed typo
  CODE_OF_CONDUCT.md
Labels: documentation, review

#878 #876 fixed tentacle manager requirement version
  requirements.txt
  tools/__init__.py
Labels: bug, review, tentacles

#881 added exit confirm on tentacle config modification
  interfaces/web/static/js/common/util.js
  interfaces/web/static/js/components/config_tentacle.js
  interfaces/web/templates/config_tentacle.html
Labels: UX/UI, review

#883 increased community tops count
  config/__init__.py
Labels: review

#882 fixed code of conduct and setup typo
  CODE_OF_CONDUCT.md
  setup.py
Labels: documentation, review

#885 fixed never deactivated exit confirm box and web interface number repr
  interfaces/web/static/js/common/util.js
  interfaces/web/static/js/components/config_tentacle.js
Labels: UX/UI, review

#888 #887 added OS and platform info in metrics
  config/__init__.py
  interfaces/web/templates/commands.html
  tools/__init__.py
  tools/metrics/metrics_manager.py
  tools/os_util.py
Labels: documentation, review

#889 fixed usdX bug in ws
  trading/exchanges/websockets_exchanges/implementations/binance_websocket.py
Labels: bug, review, trading & exchanges

#891 Fix appveyor dependency
  appveyor.yml
Labels: CI, review

#890 updated changelog
  docs/CHANGELOG.md
Labels: review, version

#892 fixed changelog typo
  docs/CHANGELOG.md
Labels: documentation, review

#895 #894 fixed global updater bug
  evaluator/Updaters/global_price_updater.py
Labels: bug, review, trading & exchanges

#897 #896 fixed decimal display
  interfaces/web/static/js/common/util.js
Labels: UX/UI

#903 #901 fixed attribute error and added error message
  trading/exchanges/exchange_symbol_data.py
Labels: bug, trading & exchanges, user issue

#906 added recently closed orders handling
  trading/trader/orders_manager.py
  trading/trader/portfolio.py
  trading/trader/trader.py
Labels: trading & exchanges

#909 #908 fixed timeframe update time
  evaluator/Updaters/global_price_updater.py
Labels: bug, trading & exchanges

#910 removed websocket warning on binary version
  trading/exchanges/websockets_exchanges/__init__.py
Labels: UX/UI, enhancement

#911 version 0.3.5
  README.md
  config/__init__.py
  docs/CHANGELOG.md
Labels: version
