Repository Drakkar-Software/OctoBot, pull requests merged in 2019-07, with the labels that each got.

#934 Fix Config checker failed when using wildcard on pairs #900
  interfaces/web/models/dashboard.py
  tests/unit_tests/core_tests/evaluator_factory_test.py
  tests/unit_tests/trading_tests/test_exchange_manager.py
  trading/exchanges/exchange_manager.py
Labels: bug

#938 #937 fixed error with api-password
  interfaces/web/templates/components/config/exchange_card.html
  trading/exchanges/rest_exchanges/rest_exchange.py
Labels: bug

#939 improved navbar UI
  interfaces/web/static/css/style.css
  interfaces/web/templates/layout.html
Labels: UX/UI, services & interfaces

#941 Fix candle updater synchronization
  evaluator/Updaters/global_price_updater.py
Labels: bug

#942 Fix #940 retry until candle updated
  evaluator/Updaters/global_price_updater.py
Labels: enhancement

#944 added switch design for tentacle config checkboxes
  interfaces/web/static/js/common/json_editor_settings.js
  interfaces/web/templates/config.html
  tools/dict_util.py
Labels: UX/UI, services & interfaces

#943 swapped config and backtesting in navbar
  interfaces/web/templates/layout.html
Labels: UX/UI, services & interfaces

#945 version 0.3.6
  README.md
  config/__init__.py
  docs/CHANGELOG.md
Labels: version

#948 Add 6h timeframe
  config/__init__.py
Labels: enhancement

#950 Migrate config file to user folder #949
  .gitignore
  config/__init__.py
  config/config.py
  tools/config_manager.py
Labels: enhancement

#953 [Docker] improve dockerfile
  .dockerignore
  Dockerfile
Labels: docker

#952 fix kraken orders
  trading/exchanges/rest_exchanges/rest_exchange.py
  trading/trader/trader.py
Labels: bug, trading & exchanges
