Repository Drakkar-Software/OctoBot, pull requests merged in 2019-01, with the labels that each got.

#500 #494 [Evaluator Config] Improve default
  config/default_evaluator_config.json
Labels: enhancement, review

#503 #502 [Setup] Update and improve setup.py
  config/__init__.py
  launcher.py
  setup.py
Labels: enhancement, review

#504 Remove launcher
  .coveragerc
  README.md
  config/__init__.py
  docs/delivery/launcher.spec
  docs/delivery/windows_delivery.ps1
  interfaces/gui/launcher/__init__.py
  interfaces/gui/launcher/launcher_app.py
  interfaces/gui/launcher/launcher_controller.py
  launcher.py
  setup.py
Labels: enhancement, review

#507 Updated README
  README.md
Labels: review

#511 Migrate tentacles branch for async
  config/__init__.py
Labels: enhancement, review

#513 Update README
  README.md
Labels: enhancement, review

#508 Implement travis & appveyor CI release
  .travis.yml
  appveyor.yml
  dev_requirements.txt
  docs/delivery/start.spec
Labels: review, version

#522 Fix appveyor release branch
  appveyor.yml
Labels: CI, review

#528 [Docker] Migrate to python:3.7.2-slim-stretch
  Dockerfile
  docs/install/linux_dependencies.sh
Labels: docker, review

#529 Update readme
  README.md
Labels: enhancement, review

#535 #533 added telegram usernames whitelist
  config/__init__.py
  interfaces/telegram/bot.py
  interfaces/trading_util.py
  interfaces/web/templates/components/config/editable_config.html
  interfaces/web/templates/components/config/service_card.html
  interfaces/web/templates/config.html
  services/telegram_service.py
Labels: review, services & interfaces

#537 #536 updated raspberry python installation
  docs/install/raspberry-pre-install.sh
Labels: enhancement, review

#542 Migrate services to async
  octobot.py
  services/abstract_service.py
  services/reddit_service.py
  services/service_creator.py
  services/telegram_service.py
  services/twitter_service.py
  services/web_service.py
  tools/commands.py
Labels: enhancement, review

#512 [Matrix] Migrate to dataclass
  config/__init__.py
  evaluator/__init__.py
  evaluator/evaluator_matrix.py
Labels: enhancement, review

#551 Migrate datacollector async
  backtesting/collector/data_collector.py
  backtesting/collector/exchange_collector.py
  tools/commands.py
Labels: enhancement, review

#531 Improve travis tests and add macos
  .travis.yml
  dev_requirements.txt
Labels: CI, review

#555 Fix travis coveralls push
  .travis.yml
Labels: review

#556 Update README docker command
  README.md
Labels: documentation, review

#557 Dockerfile improvements
  Dockerfile
  docs/install/linux_dependencies.sh
Labels: docker, review

#558 Improve appveyor test run
  appveyor.yml
Labels: CI, review, tests

#554 Add macos release and checksum in logs
  .travis.yml
Labels: CI, review, version

#559 Refactor services constants
  config/__init__.py
  interfaces/web/templates/components/config/service_card.html
  services/__init__.py
  services/abstract_service.py
  services/gmail_service.py
  services/reddit_service.py
  services/telegram_service.py
  services/twitter_service.py
  services/web_service.py
  tools/notifications.py
Labels: review, services & interfaces

#552 Add error log when started with sudo
  config/__init__.py
  tools/__init__.py
Labels: enhancement, review

#560 Implement notifier project
  config/__init__.py
  interfaces/web/web_app.py
  requirements.txt
  services/__init__.py
  services/notifier_service.py
  services/notifier_service_factory.py
  services/service_creator.py
  tools/notifications.py
Labels: dependent, review, services & interfaces

#566 [CI] Add pip cache for appveyor
  appveyor.yml
Labels: CI, review

#568 #561 added web interface notifiers handling and changed notification Service suffix
  config/__init__.py
  interfaces/web/models/configuration.py
  services/abstract_service.py
  services/notifier_service.py
  services/notifier_service_factory.py
  services/reddit_service.py
  services/service_creator.py
  services/telegram_service.py
  services/twitter_service.py
  services/web_service.py
  tools/dict_util.py
  tools/notifications.py
Labels: review, services & interfaces

#564 Create setup.py
  .travis.yml
  README.md
  dev_requirements.txt
  interfaces/gui/app/__init__.py
  interfaces/gui/app/main_app.py
  setup.py
  start.py
  tools/tentacle_creator/__init__.py
Labels: CI, dependent, enhancement, review

#563 [Notifications] Migrate to async
  interfaces/web/__init__.py
  octobot.py
  services/notifier_service.py
  services/telegram_service.py
  services/twitter_service.py
  tools/notifications.py
  trading/trader/modes/abstract_mode_decider.py
  trading/trader/order_notifier.py
  trading/trader/trader.py
Labels: review, services & interfaces

#569 [CI] Fix CI release process
  .travis.yml
  setup.py
Labels: CI, review, version

#574 Fix travis deploy
  .travis.yml
  appveyor.yml
  config/__init__.py
Labels: CI, review

#579 Fix octobot restart
  tools/commands.py
Labels: bug, review

#577 Add pypi download per month
  README.md
Labels: enhancement, review

#580 Update readme to integrate pip install
  README.md
Labels: documentation, review

#581 #572 added donation addresses
  interfaces/web/templates/footer.html
Labels: enhancement, review, services & interfaces

#583 updated contact email address
  CODE_OF_CONDUCT.md
Labels: enhancement, review

#584 [Bug] Fix notify all when no twitter service
  tools/notifications.py
Labels: bug, review

#597 #596 now won't spam "can't get matching symbol"
  trading/exchanges/exchange_dispatcher.py
  trading/trader/trades_manager.py
Labels: enhancement, review

#602 #600 added annoucements handling
  config/__init__.py
  interfaces/web/advanced_templates/advanced_index.html
  interfaces/web/advanced_templates/advanced_layout.html
  interfaces/web/api/metadata.py
  interfaces/web/static/js/components/dashboard.js
  interfaces/web/templates/index.html
  interfaces/web/templates/layout.html
  start.py
Labels: UX/UI, enhancement, review, services & interfaces

#589 Moving files from OctoBot to OctoBot-Binary
  .travis.yml
  README.md
  appveyor.yml
  dev_requirements.txt
  docs/delivery/start.spec
  docs/delivery/travis_delivery.sh
  docs/delivery/windows_delivery.ps1
  docs/install/windows_installer.bat
Labels: review

#612 #611 updated changelog
  docs/CHANGELOG.md
Labels: documentation, review

#610 #609 fixed telegram wrong warning
  services/abstract_service.py
  services/service_creator.py
  services/telegram_service.py
  services/web_service.py
Labels: bug, review, services & interfaces

#622 #621 now do not modify advanced classes list when asking for all clas…
  evaluator/Util/advanced_manager.py
Labels: bug, review, services & interfaces, tentacles

#623 factorized strings and improved multi_line help message
  tools/tentacle_manager/tentacle_manager.py
Labels: enhancement, review

#626 #624 fixed offline announcements
  interfaces/web/api/metadata.py
  tools/external_resources_manager.py
Labels: bug, review, services & interfaces

#625 Fix pre_requirements for binary
  pre_requirements.txt
Labels: enhancement, review

#627 Remove pandas
  pre_requirements.txt
Labels: enhancement, review

#628 added simplifiedpytrends requirement instead of pytrends
  requirements.txt
Labels: enhancement, evaluators, review

#634 [Version] 0.3.1
  README.md
  config/__init__.py
  docs/CHANGELOG.md
Labels: dependent, review, version

#637 Fix travis deployment without testing
  .travis.yml
Labels: CI, bug, review

#643 #639 added back button on symbol data and made all title h1
  interfaces/web/templates/data_collector.html
  interfaces/web/templates/index.html
  interfaces/web/templates/logs.html
  interfaces/web/templates/symbol_market_status.html
  interfaces/web/templates/trades.html
  interfaces/web/templates/trading.html
Labels: UX/UI, review

#645 #644 now handles first use default config values and web interface de…
  config/__init__.py
  config/config.py
  services/abstract_service.py
  services/notifier_service.py
  start.py
  tools/config_manager.py
  trading/exchanges/exchange_manager.py
  trading/exchanges/rest_exchanges/rest_exchange.py
  trading/exchanges/websockets_exchanges/abstract_websocket.py
  trading/exchanges/websockets_exchanges/implementations/binance_websocket.py
Labels: enhancement, review

#646 now better handles offline mode
  interfaces/web/static/js/components/commands.js
  trading/exchanges/websockets_exchanges/implementations/binance_websocket.py
Labels: UX/UI, review
