Repository Drakkar-Software/OctoBot, pull requests merged in 2019-02, with the labels that each got.

#648 #647 fixed currrency addition
  interfaces/web/static/js/components/configuration.js
  interfaces/web/templates/components/config/currency_card.html
  interfaces/web/templates/components/config/editable_config.html
  interfaces/web/templates/components/config/service_card.html
Labels: bug, review, services & interfaces

#649 [Web Interface] Improve performance by using a dedicated server
  interfaces/web/web_app.py
Labels: enhancement, review, services & interfaces

#650 added virtual desc in real trader stop orders
  interfaces/web/templates/macros/tables.html
Labels: UX/UI, review

#652 fixed rare ungraceful stop
  trading/trader/orders_manager.py
Labels: bug, review

#654 Migrate tentacle manager to external repository
  config/__init__.py
  interfaces/web/models/tentacles.py
  requirements.txt
  setup.py
  start.py
  tools/commands.py
  tools/tentacle_creator/__init__.py
  tools/tentacle_creator/templates/Mode_config.template
  tools/tentacle_creator/templates/Mode_tentacle.template
  tools/tentacle_creator/templates/RealTime_tentacle.template
  tools/tentacle_creator/templates/Social_tentacle.template
  tools/tentacle_creator/templates/Strategies_config.template
  tools/tentacle_creator/templates/Strategies_tentacle.template
  tools/tentacle_creator/templates/TA_tentacle.template
  tools/tentacle_creator/templates/Util_tentacle.template
  tools/tentacle_creator/templates/description_tentacle.template
  tools/tentacle_creator/tentacle_creator.py
  tools/tentacle_manager/__init__.py
  tools/tentacle_manager/tentacle_manager.py
  tools/tentacle_manager/tentacle_package_manager.py
  tools/tentacle_manager/tentacle_package_util.py
  tools/tentacle_manager/tentacle_util.py
Labels: review, tentacles

#657 Add order book and recent trades data for realtime evaluators
  config/__init__.py
  evaluator/RealTime/realtime_evaluator.py
  evaluator/Strategies/strategies_evaluator.py
  trading/exchanges/exchange_dispatcher.py
  trading/exchanges/exchange_symbol_data.py
  trading/exchanges/rest_exchanges/rest_exchange.py
Labels: review, tentacles, trading & exchanges

#658 Migrate from beta branch to master
  .travis.yml
Labels: CI, review

#660 [Python3.7] Refactor Order and Trade classes
  trading/trader/order.py
  trading/trader/trade.py
  trading/trader/trader.py
Labels: enhancement, review

#676 renovate ignore tentacle manager
  renovate.json
Labels: review

#680 removed double errors log
  tools/logging/logging_util.py
Labels: UX/UI, enhancement, review

#682 #681 Improved checkboxes design
  interfaces/web/templates/backtesting.html
  interfaces/web/templates/tentacles.html
Labels: UX/UI, review

#683 added warning on websocket import error
  trading/exchanges/websockets_exchanges/__init__.py
Labels: review, trading & exchanges

#685 #684 fixed telegram message size limit handling
  interfaces/bots/interface_bot.py
  interfaces/bots/telegram/bot.py
Labels: bug, review, services & interfaces

#688 #687 improved readability
  interfaces/web/static/js/common/candlesticks.js
Labels: UX/UI, review
