Repository Drakkar-Software/OctoBot, pull requests merged in 2019-03, with the labels that each got.

#703 #702 now force portfolio update when requesting for it
  interfaces/trading_util.py
  trading/trader/trades_manager.py
Labels: bug, review, trading & exchanges

#698 #697 now cancel linked orders before selling and don't stop updating …
  trading/trader/order.py
  trading/trader/orders_manager.py
  trading/trader/trader.py
Labels: bug, review, trading & exchanges

#709 updated telegram image
  README.md
Labels: documentation, review

#720 portfolio pie chart now start with blue
  interfaces/web/static/js/common/cst.js
  interfaces/web/static/js/common/util.js
Labels: UX/UI, review

#714 #713 fixed /fees command error on stop loss orders
  trading/trader/order.py
  trading/trader/trades_manager.py
Labels: bug, review, trading & exchanges

#719 version 0.3.2-beta
  README.md
  config/__init__.py
  docs/CHANGELOG.md
Labels: review, version

#723 changed tentacles branch to master
  config/__init__.py
Labels: review

#724 fixed trader simulator start
  octobot.py
Labels: bug, review

#729 fixed default port
  services/web_service.py
Labels: review, services & interfaces

#726 #removed fstring from start.py
  start.py
Labels: bug, review

#727 added identifier to simulator order manager logs
  trading/trader/orders_manager.py
Labels: review, trading & exchanges

#737 [Code cleanup] Refactor code assignation with None check
  evaluator/Strategies/strategies_evaluator.py
  tests/test_utils/data_bank.py
  tools/dict_util.py
  trading/exchanges/exchange_simulator/exchange_simulator.py
  trading/trader/modes/abstract_trading_mode.py
Labels: review

#744 fixed simulated trades history in chart
  interfaces/web/models/dashboard.py
  trading/trader/trader.py
Labels: bug, review, services & interfaces

#745 Fix trader unused OM
  octobot.py
  tests/unit_tests/trading_tests/test_orders_manager.py
  tests/unit_tests/trading_tests/test_trader.py
  trading/trader/trader.py
Labels: enhancement, review

#746 #fixed used order manager fix bugs
  interfaces/__init__.py
  interfaces/bots/telegram/bot.py
  interfaces/trading_util.py
  tests/unit_tests/tools_tests/test_config_manager.py
  tests/unit_tests/trading_tests/test_trades_manager.py
  tools/config_manager.py
  trading/trader/trades_manager.py
Labels: bug, review

#757 #756 ensured call_order_update_callback is always called
  trading/trader/orders_manager.py
Labels: bug, review
