Repository Drakkar-Software/OctoBot, pull requests merged in 2019-04, with the labels that each got.

#763 fixed asyncio with tests
  tests/endurance_tests/start_bot_test.py
  tests/functional_tests/launch_test/launch_test.py
Labels: bug, review, tests

#765 Add a warning when duplicate tentacle names
  evaluator/Util/advanced_manager.py
Labels: enhancement, review

#762 Implement symbol wildcard
  config/__init__.py
  core/evaluator_factory.py
  interfaces/web/models/configuration.py
  interfaces/web/models/dashboard.py
  tests/unit_tests/trading_tests/test_exchange_manager.py
  trading/exchanges/exchange_manager.py
  trading/exchanges/websockets_exchanges/abstract_websocket.py
  trading/trader/trader.py
  trading/trader/trades_manager.py
Labels: enhancement, review

#769 Add core evaluator factory tests
  core/evaluator_factory.py
  evaluator/symbol_evaluator.py
  tests/unit_tests/core_tests/__init__.py
  tests/unit_tests/core_tests/evaluator_factory_test.py
  trading/exchanges/exchange_manager.py
Labels: review, tests

#771 fixed slow backtesting
  trading/exchanges/exchange_simulator/exchange_simulator.py
Labels: backtesting, bug, review

#770 Add pytest test duration
  .travis.yml
Labels: review, tests

#774 fixed get_traded_pairs limit case
  trading/exchanges/exchange_manager.py
  trading/exchanges/exchange_simulator/exchange_simulator.py
Labels: bug, review

#775 Fix pytest warning summary
  .travis.yml
Labels: review

#772 Improve endurance run bot test duration
  tests/endurance_tests/start_bot_test.py
Labels: review, tests

#778 factorized code and prevented pytest import from regular code
  backtesting/backtesting_util.py
  tests/endurance_tests/start_bot_test.py
  tests/functional_tests/launch_test/launch_test.py
  tests/test_utils/bot_management.py
Labels: bug, review

#779 added telegram community link
  interfaces/web/templates/footer.html
Labels: UX/UI, review, services & interfaces

#783 #740 attempts to fix timeout user issue
  config/__init__.py
Labels: bug, review

#784 added traded pairs in metrics
  interfaces/web/templates/commands.html
  tools/metrics_manager.py
Labels: enhancement, review

#790 [Web Interface] Catch exception when address is already used
  interfaces/web/web_app.py
Labels: review, services & interfaces

#794 fixed exception in missing exchange api key
  tools/config_manager.py
Labels: bug, review, trading & exchanges

#796 added utility methods
  trading/trader/modes/abstract_trading_mode.py
  trading/trader/trader.py
Labels: review, tentacles

#798 Fix exchange dispatcher
  trading/exchanges/exchange_dispatcher.py
Labels: bug, review

#800 WIP [Websocket] new websocket management
  backtesting/backtester.py
  core/consumers_producers/__init__.py
  core/consumers_producers/consumer.py
  core/consumers_producers/consumer_producer.py
  core/consumers_producers/consumer_producers.py
  core/consumers_producers/consumers_producer.py
  core/consumers_producers/consumers_producers.py
  core/consumers_producers/producers.py
  core/exchange/__init__.py
  core/exchange/balance.py
  core/exchange/ohlcv.py
  core/exchange/order_book.py
  core/exchange/orders.py
  core/exchange/recent_trade.py
  core/exchange/ticker.py
  requirements.txt
  tests/unit_tests/trading_tests/implementations/test_binance_websocket.py
  tests/unit_tests/trading_tests/test_exchange_manager.py
  tests/unit_tests/trading_tests/test_exchange_market_status_fixer.py
  trading/__init__.py
  trading/exchanges/__init__.py
  trading/exchanges/abstract_exchange.py
  trading/exchanges/exchange_dispatcher.py
  trading/exchanges/exchange_manager.py
  trading/exchanges/exchange_simulator.py
  trading/exchanges/exchange_symbol_data.py
  trading/exchanges/rest_exchange.py
  trading/exchanges/websockets/__init__.py
  trading/exchanges/websockets/abstract_websocket.py
  trading/exchanges/websockets/binance_websocket.py
  trading/exchanges/websockets/octobot_websocket.py
  trading/exchanges/websockets/websocket_callbacks.py
  trading/exchanges/websockets_exchanges/implementations/__init__.py
  trading/trader/orders_manager.py
  trading/trader/trades_manager.py
Labels: enhancement, review, trading & exchanges

#803 added reference market getter from trader
  trading/trader/trader.py
Labels: review, trading & exchanges

#806 add filter on cancel orders
  interfaces/trading_util.py
  interfaces/web/api/trading.py
  interfaces/web/static/js/components/trading.js
  interfaces/web/templates/trading.html
  trading/trader/trader.py
Labels: UX/UI, review

#805 [Version] prepare 0.3.3
  README.md
  config/__init__.py
  config/config_schema.json
  docs/CHANGELOG.md
Labels: review

#808 add CodeOwners
  .github/CODEOWNERS
Labels: review

#812 fixed tentacle management interface git branch
  interfaces/web/models/tentacles.py
Labels: bug, review, services & interfaces, tentacles

#809 #782 [Notifiers] Remove
  config/__init__.py
  interfaces/web/models/configuration.py
  requirements.txt
  services/__init__.py
  services/notifier_service.py
  services/notifier_service_factory.py
  services/service_creator.py
  tools/notifications.py
Labels: review, services & interfaces

#813 [Docker] Raspberry image
  docs/install/arm32v7/Dockerfile
Labels: review

#817 Navbar current selection UX improvement
  interfaces/web/advanced_templates/advanced_evaluator_config.html
  interfaces/web/advanced_templates/advanced_index.html
  interfaces/web/advanced_templates/advanced_layout.html
  interfaces/web/advanced_templates/advanced_matrix.html
  interfaces/web/advanced_templates/advanced_strategy_optimizer.html
  interfaces/web/static/css/style.css
  interfaces/web/templates/backtesting.html
  interfaces/web/templates/commands.html
  interfaces/web/templates/community.html
  interfaces/web/templates/config.html
  interfaces/web/templates/data_collector.html
  interfaces/web/templates/index.html
  interfaces/web/templates/layout.html
  interfaces/web/templates/logs.html
  interfaces/web/templates/portfolio.html
  interfaces/web/templates/symbol_market_status.html
  interfaces/web/templates/tentacle_packages.html
  interfaces/web/templates/tentacles.html
  interfaces/web/templates/trades.html
  interfaces/web/templates/trading.html
Labels: UX/UI, review

#825 allowed bot start with mistakes in exchange config
  interfaces/trading_util.py
  trading/trader/trader.py
Labels: bug, review, trading & exchanges

#827 #826 now update last candle display
  interfaces/web/__init__.py
Labels: bug, review, services & interfaces

#829 [CI] Fix setup.py dependencies error
  pre_requirements.txt
Labels: CI, review

#833 #832 now start with error log if trading mode can't init
  trading/trader/modes/abstract_trading_mode.py
Labels: bug, review, tentacles

#822 trading pair and timeframe error message
  core/evaluator_factory.py
  trading/exchanges/exchange_manager.py
Labels: bug, review, trading & exchanges

#836 Update contributing style
  CONTRIBUTING.md
Labels: documentation, review

#840 #839 improved backtesting files display
  backtesting/collector/data_file_manager.py
  interfaces/web/templates/backtesting.html
  interfaces/web/templates/data_collector.html
Labels: UX/UI, backtesting, review

#850 coinbase pro market order adaptation
  trading/exchanges/rest_exchanges/rest_exchange.py
Labels: review, trading & exchanges

#852 Update README
  README.md
Labels: documentation, review
